### ISSUE TITLE
Gives no output if maximum height = 0

### ISSUE THREAD

**Issue by ILikeHerculePoirot** [SohamGi/Projectile-motion-python-code#2]
It gives no output if the maximum height is zero. In this case, the launch angle would be 0 degrees. This is because, you are only setting the initial velocity and launch angle to zero. You are not printing it. Also, you need to set time of flight to zero and print it. Also, you could add GUI using tkinter (Recommended because you need to display textboxes on the screen)

**Comment by SohamGi** [comment]
Thanks for pointing out. I will add the print statement .

**Comment by SohamGi** [comment]
I will take a look at GUI. Thank you for informing.

**Comment by ILikeHerculePoirot** [comment]
In github, if you fix an issue, you should close the issue (You have to close this issue and the other one).

**Comment by ILikeHerculePoirot** [comment]
(I closed it for you)

**Comment by SohamGi** [comment]
thanks alot

**Comment by ILikeHerculePoirot** [comment]
Welcome.
